### ISSUE TITLE
Unsafe SIMD loop(s?) in WeightedAve

### ISSUE THREAD

**Issue by pdmullen** [PrincetonUniversity/athena#349]
**Summary of issue**

@changgoo recently brought to my attention that the `viscous_diffusion_sts`  test problem fails on Jenkins with Intel compilers (e.g., `intel/18.0/64/18.0.3.222`).   The problem passes with all other (tested) non-Intel compilers.  Furthermore, the test passes on my Macbook using Intel oneAPI.

I recently discovered that the `viscous_diffusion_sts` test passes with `intel/18.0/64/18.0.3.222` when applying the `--cflag=-fp-model=strict` flag (see https://github.com/PrincetonUniversity/athena/issues/340#issuecomment-748982364).  Today, I discovered that the test actually passes by just disabling SIMD vectorization with `-qno-openmp-simd`.  After a long, painful journey, I isolated the issue to this loop: 

https://github.com/PrincetonUniversity/athena/blob/d19655031a8ce26ee1c662974ad3bb98f948dc53/src/mesh/weighted_ave.cpp#L99-L103

i.e., if I remove `#pragma omp simd` from this loop, I find that `viscous_diffusion_sts` passes with Intel compilers.  @changgoo, can you confirm this on Jenkins?

I see no reason why this loop would be problematic with SIMD...does anyone else see any reason why?

Altogether, I am confused about why this particular SIMD loop is failing, but I'm also concerned about the other SIMD loops appearing in `weighted_ave.cpp`.  They all follow the same format.  For those using RKL2 STS with Intel compilers, beware~

**Comment by felker** [comment]
From Intel:
>  after changing the  `-xhost` flag for `-march=skylake-avx512` in the `configure.py` for the `icpc` option  we no longer see the issue after we run the regression test. Do you think maybe you can try it and let me know if that prevented the issue from causing NaN.

@pdmullen can you try this compiler flag on the Skylake system you were using? Was the head node where you compiled also Skylake?

Still, this workaround doesnt make sense to me, since even if the head node was not Skylake, it should still compile SIMD-safe code using the instruction set which is a strict subset of the one supported on Skylake. And it wont work nor explains @changgoo's observations on Perseus's Broadwell nodes.

**Comment by pdmullen** [comment]
This didn't seem to work for me, @felker.  When compiling and running the `viscous_diffusion_sts` problem on an `Intel(R) Xeon(R) Gold 6132 CPU SKX` node, I find the following

`Compilation command:  icpc  -O3 -std=c++11 -ipo -xhost -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -qoverride-limits -diag-disable 3180`  **FAILS**

`  Compilation command:        icpc  -O3 -std=c++11 -ipo -xhost -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -qoverride-limits -diag-disable 3180 -qopt-zmm-usage=high` **PASSES**

`  Compilation command:        icpc  -O3 -std=c++11 -ipo -march=skylake-avx512 -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -qoverride-limits -diag-disable 3180` **FAILS**

**Comment by felker** [comment]
I too tested the compiler flag change using  `icpc (ICC) 19.0.4.243 20190416` on Intel(R) Xeon(R) Platinum 8180M CPU @ 2.50GHz and it did not help. Upon further clarification, the workaround only worked for `icpc` in the latest oneAPI drops, `2021.x`: https://software.intel.com/content/www/us/en/develop/articles/intel-cpp-compiler-release-notes.html
(which had barely been released when this issue was first opened; I was just made aware of it today)

To my knowledge, 19.1.x comprised all the releases through 2020 via the Parallel Studio XE licensing model of old. In other words, we will need to wait for sys admins to install oneAPI on the computers of interest in order to consistently work around this bug even with the "classic" Intel C++ compiler.
