### ISSUE TITLE
In spherical polar coordinates, theta limits not symmetric about pi/2 cause geometric source term errors

### ISSUE THREAD

**Issue by msbc** [PrincetonUniversity/athena#354]
In spherical polar coordinates, if you set theta limits to not be symmetric about pi/2 then the geometric source terms give the wrong value. 

**Summary of issue**

This was only noticed in a 1D Parker wind calculation (i.e. nx2=nx3=1) and lead to an inaccurate solution.

PS: I'm on paternity leave, so I don't have time to fill this out properly, but still wanted to document it.

**Steps to reproduce**

Set x2min, x2max such that pi/2-x2min != x2max-pi/2.

**Comment by apbailey** [comment]
Resurrecting this issue since I independently ran into this problem and did some diagnosing. In my case I set up a 1d radial profile with density=pressure=1 and v=0 everywhere, reflecting BCs, and when x2 limits were not symmetric about pi/2, the profile developed large amplitude spurious theta-velocities which removed significant mass and destroyed the 1D equilibrium. In this case the offending issue was an imbalance between the geometric source term and the flux divergence. Looking at the theta-momentum equation

$$\frac{\partial\left(\rho v_\theta\right)}{\partial t} + \nabla\cdot\left(M_{r\theta}\hat{r} + M_{\theta \theta}\hat{\theta} + M_{\phi \theta}\hat{\phi}\right) = \frac{\cot\theta}{r}M_{\phi\phi} - \frac{M_{\theta r}}{r}$$

for this equilbrium with v=0 normally you have  the only non-zero terms $\nabla\cdot M_{\theta \theta}\hat{\theta} = \cot\theta M_{\phi\phi} /r$ so $\partial_t(\rho v_\theta)=0$. Both of these terms are nonzero and in particular the flux divergence is nonzero because the upper and lower theta-face areas are generally unequal in spherical coordinates. While the geometric source term is added as normal in 1D, in add_flux_divergence the non-zero flux-divergence in the x2-direction is not added. Of course when theta limits are symmetric about $\pi/2$, the $\cot\theta$ in the geometric source term vanishes and this imbalance does not arise. For other geometries and 2D spherical polar, this issue does not arise since the upper and lower higher dimensional faces have equal areas (cartesian, x2/x3 face cylindrical, x3 face spherical) so the flux divergences will vanish. 

Adding the x2 flux divergence back in 1d spherical is probably a bad fix since it would require pointlessly calculating the x2-flux or fudging in some flux divergence to what equivalently amounts to having the geometric source term vanish. At least throwing an error if x2 limits are asymmetric in 1d spherical seems reasonable enough to stop people like me from running into this problem again. I suppose there may still be an issue if someone tries to run 1D spherical with non-zero $v_\theta$ because then you have a non-zero $\rho v_r v_\theta/r$ geometric source term and no $\rho v_\theta v_\theta$ flux divergence term, but like Chris, I don't know what it means to do a 1D spherical problem with nonzero $v_\theta$ or what the use-case would be.

**Comment by felker** [comment]
I think a runtime message triggered when `std::abs((pmy_mesh_->mesh_size.x2max - PI/2.0) - ( PI/2.0 - pmy_mesh_->mesh_size.x1min ) )<= std::numeric_limits<Real>::epsilon()` is the best solution. Added next to this error:
https://github.com/PrincetonUniversity/athena/blob/71da5c314c4cbb413ff35376ec5ca91fc03d138f/src/bvals/utils/check_polar.cpp#L129-L157

And I think it should be a `### FATAL ERROR`; I can't see a reason why a typical user would want to run such a simulation in 1D. And if a sophisticated user wants to do so, they need to be knowledgeable enough to re-add x2 flux divergence terms,  etc. in the source code, so they can override the safety check easily. 

Regarding the nonzero theta velocity case, our options are:
- do nothing
- add a new section "1D Polar Coordinates" with notes to Wiki page https://github.com/PrincetonUniversity/athena/wiki/Coordinate-Systems-and-Meshes 
- emit a (nonfatal) runtime warning for **any** 1D spherical-polar simulation, reference this issue and/or Wiki page. E.g. `"### Warning in BoundaryValues constructor. The 1D spherical-polar coordinates solver assumes globally zero x2 polar velocities. This condition is left to the user to confirm"`
  - might be too confusing/noisy/aggressive for users?
- for any 1D spherical-polar simulation , flip a flag:
  - The flag enables a check of the initial condition that `max(abs(` of  `u(IM2, :, :, :)` is zero; emit fatal error if encountered.
  - The flag enables a check at every timestep, that `max(abs(` of `w(IVY, :, :, :)` and/or `u(IM2, :, :, :)` is zero; emit fatal error if encountered. 
  - Both seem too aggressive and expensive, IMHO

I don't have a strong opinion of the latter situation. Mind opening a PR addressing the former @apbailey?

**Comment by apbailey** [comment]
Adding the error msg to CheckPolar doesn't address the issue very well because it's only called when x2 boundaries are set to polar or polar-wedge in which case it will probably trigger the fatal error requiring x2max=PI anyways. Since polar_wedge doesn't even really make sense in 1D, if other users are anything like me they will be setting x2=reflecting or periodic for 1D problem for which the error check would probably make sense to go somewhere like spherical coordinate initialization: https://github.com/PrincetonUniversity/athena/blob/71da5c314c4cbb413ff35376ec5ca91fc03d138f/src/coordinates/spherical_polar.cpp#L34C1-L52C4

**Comment by felker** [comment]
I meant to suggest adding the new error/warning(s) in that general location in that file, not within the conditional regarding `polar_wedge`, `polar` BCs etc., but you are correct that the function is currently only called for 
https://github.com/PrincetonUniversity/athena/blob/71da5c314c4cbb413ff35376ec5ca91fc03d138f/src/bvals/bvals.cpp#L95-L101

Would need to create a new function and/or call it `if (std::strcmp(COORDINATE_SYSTEM, "spherical_polar") == 0)`, if we went that route. Or your suggested spot is fine too.

What is your opinion on the vtheta issue?

**Comment by apbailey** [comment]
I agree that fatal warning on nonzero vtheta is probably overkill but think any of the other options are fine. I lean towards a couple lines in the wiki like example below, as I think the most relevant uses for 1D spherical is probably newer users and simple problems, so best to probably state explicitly somewhere. The fact this issue has persisted for so long could be an indication that few people are using this setup anyway so doing nothing is not so bad or a non-fatal warning is probably not so intrusive

#### 1D Polar Coordinates
Spherically symmetric problems should be solved in 1D with --coord=spherical_polar, in which case the x2 limits of the mesh should be made symmetric about $\pi/2$. Non-zero polar and azimuthal velocities are not supported in 1D and should be initialized to zero.

-- will open PR for fatal x2 limit warning

**Comment by felker** [comment]
I added your text to https://github.com/PrincetonUniversity/athena/wiki/Coordinate-Systems-and-Meshes#1d-polar-coordinates
