### ISSUE TITLE
method for gravity source terms should be documented

### ISSUE THREAD

**Issue by BenWibking** [PrincetonUniversity/athena#450]
The methods paper for the gravity source terms [1] does not appear to be the method actually used in the code. The method used for the gravitational source terms should be documented (perhaps in the wiki?), especially so that users understand that the implementation is not the same as that of the methods paper.

[1] https://arxiv.org/abs/2012.01340.

**Comment by pdmullen** [comment]
Thanks @BenWibking for raising the issue.  I do not have permissions to edit the Wiki, but the Wiki should reflect something to the effect of: 

> Updates to momenta and total energy due to self-gravity are added via source terms, **not** via the divergence of a gravitational stress tensor or gravitational energy "flux", respectively.  Source terms are added following the prescription detailed in MHG2020 (https://arxiv.org/abs/2012.01340), with the exception that the energy source term does not use the time-averaged gravitational potential.  With this simplification, total energy is not conserved to round-off error.  Momentum conservation is determined by the accuracy of the gravitational potential.  

@tomidakn could you add something to this effect in the Wiki?

**Comment by felker** [comment]
Which page?
https://github.com/PrincetonUniversity/athena/wiki/Self-Gravity-with-FFT
or
https://github.com/PrincetonUniversity/athena/wiki/Self-Gravity-with-Multigrid
or something else?

**Comment by pdmullen** [comment]
Both.

**Comment by pdmullen** [comment]
Thanks @felker.  Also, these lines should be removed from https://github.com/PrincetonUniversity/athena/wiki/Self-Gravity-with-FFT:

~The momentum source term due to the gravitational force is included in the flux calculation by adding the gravitational tensor. See athena/src/hydro/gravity_fluxes.cpp.~

~The energy source term due to the gravitational energy flux is separately added as a source term. See athena/src/hydro/srcterm/gravity.cpp.~
