### ISSUE TITLE
Remove unused DEBUG macro

### ISSUE THREAD

**Issue by felker** [PrincetonUniversity/athena#531]
Following https://github.com/PrincetonUniversity/athena/pull/496#issuecomment-1610870084

If you configure with `-debug` and compile, our script sets
https://github.com/PrincetonUniversity/athena/blob/8b29a3ecf93b22a5a1d5a937c613085c1824545e/configure.py#L585-L587
and defines the `DEBUG` preprocessor macro:
https://github.com/PrincetonUniversity/athena/blob/8b29a3ecf93b22a5a1d5a937c613085c1824545e/src/defs.hpp.in#L79

This is currently unused in `src/`. Do we 1) remove it 2) allow future `#ifdef DEBUG` in `master`, or 3) keep it defined but unused in `master` so forked or developmental features can use it easily?

**Comment by tomidakn** [comment]
I think it is OK to keep this option. However, the original policy of Athena++ is minimizing use of  #ifdef. The problem of #ifdef is codes within the #ifdef - #endif block are not compiled and therefore not error checked (This is of course necessary for external library calls). Modern compilers should be able to optimize C++ if statements if they can be determined at the time of compilation. So I prefer to keep this policy, and encourage developers to use if instead of #ifdef as much as possible.

**Comment by tomidakn** [comment]
Oh but to do so, we need to change 
> #define DEBUG
to 
> #define DEBUG 1

**Comment by felker** [comment]
@tomidakn I agree that `if (DEBUG) { ...} ` is highly preferred to `#ifdef DEBUG`. But I wonder if we shouldn't also be very strict about how many `if (DEBUG) { ...} ` sections get merged to `master`. And also, the switch might make more sense to be decoupled from compiling with `-g`. Sometimes you will want the debug symbols in your executable without a bunch of your verbose `DEBUG` code running. Although I guess in that case you can manually add the `--cflag=-g` instead of `-debug` convenience flag for `configure.py`

**Comment by tomidakn** [comment]
This is a good point. Indeed, I agree that we should separate the debugger (-g) option and the DEBUG flag. Possibly, it may be better to have a separate DEBUG flag for each module. I also understand that it is better to reduce DEBUG codes as much as possible in the master.

I am not sure if this is the best yet, but one possibility is separating "debug" = less optimization and "verbose" = more diagnosis messages?
