### ISSUE TITLE
Confusion while running 'athinput.magnetized_inflow'

### ISSUE THREAD

**Issue by adamdarx** [PrincetonUniversity/athena#608]
When I tried to explore /athena/inputs/mhd_gr/athinput.magnetized_inflow and configured as follows:
```sh
python3 configure.py --prob=gr_mhd_inflow -g -b --coord=kerr-schild
```
And it did successfully go thru the 'make' step and i got a corresponding executable athena. However, when I typed following code into the shell:
```sh
~/athena/bin/athena -i ~/athena/inputs/mhd_gr/athinput.magnetized_inflow
```
It reported a bug like:
```sh
### FATAL ERROR in Problem Generator
file magnetized_inflow.dat cannot be opened
```
I've just notice that in 'input file' it seems I need to provide magnetized_inflow.dat myself. But how should I get a magnetized_inflow.dat?

**Comment by c-white** [comment]
This problem is meant to implement the 2D equilibrium state described in [Gammie 1999, ApJ 522 L57](https://doi.org/10.1086/312207). Athena expects to read the profile of this state as written into a text file by a code associated with that paper, currently the last one listed [here](https://rainman.astro.illinois.edu/codelib/).
