### ISSUE TITLE
does reflecting the magnetic field at boundaries make sense?

### ISSUE THREAD

**Issue by BenWibking** [PrincetonUniversity/athena#630]
**Summary of issue**
In the current version of Athena++, the reflecting boundary conditions reflect the normal component of the magnetic field at domain boundaries, analogous to what is done for the velocity:
https://github.com/PrincetonUniversity/athena/blob/ee2b2c761df84aa863c38d2964854c4cf2c70145/src/bvals/fc/reflect_fc.cpp#L25

However, does this make sense for an axial vector like the magnetic field $\vec B$? Under reflection symmetry, the normal component of axial vectors should not change direction. Moreover, this would seem to violate the $\nabla \cdot B = 0$ involution, since the normal component would then cease to be continuous at the boundary.

**Additional comments and/or proposed solution**
I'm not sure how to fix this. The CO5BOLD code proposes various options: https://www.astro.uu.se/~bf/co5bold/7_1_5Boundary_conditions_MH.html

**Version info**
N/A

**Comment by BenWibking** [comment]
What I think should happen instead is the exact opposite: the transverse components should have their sign changed, and the normal component should have its sign unchanged.

This follows from the right-hand rule applied to current loops:
* Illustration for transverse components:
  ![image](https://github.com/user-attachments/assets/0a3a9b5f-441d-421f-8c59-2c794faf4ff8)
* Illustration for normal component:
  ![image](https://github.com/user-attachments/assets/82341963-154d-4d8c-b38a-d9fa3f51a83e)

**Comment by jmstone** [comment]
Since I have been using these BCs for so long, they make sense to me.  Reflecting BCs for the field are used when the normal component at the interface is zero.  They were originally used for MHD models of accretion disks with reflection symmetry at the midplane (equator).  There is a different BC (diode?) that can be used when the normal component of the field is NOT zero.  As Kengo says, users can add any BC they like, or if the developers feel the reflecting BCs should be deprecated that is fine by me.  Be warned, however, that reflecting BCs for the magnetic field in AthenaK work the same way as in Athena++!!

**Comment by BenWibking** [comment]
Thanks to both of you for the feedback. I'll close this issue.

**Comment by tomidakn** [comment]
I added a brief comment about this issue in [Wiki](https://github.com/PrincetonUniversity/athena/wiki/Boundary-Conditions).
