### ISSUE TITLE
Fix Turbulence Driver input flag ambiguity

### ISSUE THREAD

**Issue by tomidakn** [PrincetonUniversity/athena#634]
The [documentation](https://github.com/PrincetonUniversity/athena/wiki/Turbulence-Driver) says that we need to set `turb_flag` in the `<problem>` block (and other turbulence parameters in the `<turbulence>` block). However, I found that this is not the case, and we need to set Mesh::turb_flag in a pgen file (typically in Mesh::InitMeshData), as in `turb.cpp`. This is inconsistent.

I would like to propose the following changes:
1. Move `turb_flag` to `<turbulence>`.
2. Read `turb_flag` automatically.

Or at very least, we should update the manual to be consistent with the current implementation.

**Comment by felker** [comment]
For reference, https://github.com/PrincetonUniversity/athena/blob/ee2b2c761df84aa863c38d2964854c4cf2c70145/src/pgen/turb.cpp#L44-L57
which is also copied verbatim in the chemistry turbulence problem generator:
https://github.com/PrincetonUniversity/athena/blob/ee2b2c761df84aa863c38d2964854c4cf2c70145/src/pgen/chem_turb.cpp#L48-L61

Are there other problem generators that invoke turbulence driving that I am unaware of? If not, then it seems like a semantic issue, since the input parameter is always read into the `Mesh` class object in those cases. Maybe we could add a sentence to the Wiki that "the accompanying problem generator should read this parameter and save it to the `Mesh`" or something. Or what is your proposed alternative for 2. ?

Agreed with your point number 1.

**Comment by tomidakn** [comment]
I do not think it is necessary for this to be written in a pgen file, and I prefer that the code automatically read this flag and set it during the initialization (probably in the Mesh constructor) so that a user does not have to write it. So, I am suggesting to change the code to fit the documentation, not opposite.
